spring:
  datasource:
    url: jdbc:h2:mem:proxyshopping;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
    hikari:
      jdbc-url: jdbc:h2:mem:proxyshopping;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /my-h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
